const Sdata = [
  {
    imgsrc:
      "https://live-production.wcms.abc-cdn.net.au/993fcd282fdce29e6f2f6f633966fb1c?impolicy=wcms_crop_resize&cropH=1688&cropW=3000&xPos=0&yPos=94&width=862&height=485",
    name: "Google",
    title: "Search the world's information",
    summery: "Use Google Assistant to summarize web pages",
    link: "https://www.google.co.uk/",
  },
  {
    imgsrc:
      "https://akm-img-a-in.tosshub.com/indiatoday/images/story/202012/Netflix-New-Feature-Audio-Only_1200x768.jpeg?size=690:388",
    name: "Netflix",
    title: "Unlimited movies, TV shows and more",
    summery: "Watch anywhere. Cancel anytime",
    link: "https://www.netflix.com/in/",
  },
  {
    imgsrc:
      "https://play-lh.googleusercontent.com/G7jAks-PRl4d7IkL-s3Ir44nGyPq0Yh872N5UMwZYIJz4wG1Oj0DqoQjsAR5ddKZbQ",
    name: "Amazon",
    title: "Online Shopping India",
    summery: "Free Shipping & Cash on Delivery",
    link: "https://www.amazon.in/?&tag=googhydrabk1-21&ref=pd_sl_5szpgfto9i_e&adgrpid=155259813593&hvpone=&hvptwo=&hvadid=674893540034&hvpos=&hvnetw=g&hvrand=9334241145574719945&hvqmt=e&hvdev=c&hvdvcmdl=&hvlocint=&hvlocphy=9302218&hvtargid=kwd-64107830&hydadcr=14452_2316413&gad_source=1",
  },
  {
    imgsrc:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSUKA_UkkS2Wzw8d-AN7YP3UKn4YRVudlkNrg&s",
    name: "Instagram",
    title: "Connect with friends",
    summery: "Share what you're into with the people who get you",
    link: "https://www.instagram.com/",
  },
  {
    imgsrc:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a7/Facebook_Logo_%282019%29.png/800px-Facebook_Logo_%282019%29.png",
    name: "Facebook",
    title: "Connect with friends and the world around you",
    summery: "Share and stay connected with your friends and family",
    link: "https://www.facebook.com/",
  },
  {
    imgsrc:
      "https://cdn.vox-cdn.com/thumbor/tqTttG59bfEkJQ7ctR15NKXro_w=/0x0:1320x880/920x613/filters:focal(556x334:764x542):format(webp)/cdn.vox-cdn.com/uploads/chorus_image/image/62692391/Twitter_logo.0.jpg",
    name: "Twitter",
    title: "What's happening?",
    summery: "Join the conversation on Twitter",
    link: "https://twitter.com/",
  },
  {
    imgsrc:
      "https://www.apple.com/ac/structured-data/images/knowledge_graph_logo.png?202110180743",
    name: "Apple",
    title: "Think different",
    summery: "Discover the innovative world of Apple",
    link: "https://www.apple.com/",
  },
  {
    imgsrc:
      "https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/YouTube_Logo_2017.svg/1280px-YouTube_Logo_2017.svg.png",
    name: "YouTube",
    title: "Broadcast Yourself",
    summery: "Watch and share videos",
    link: "https://www.youtube.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/airbnb-2.svg",
    name: "Airbnb",
    title: "Vacation Rentals, Homes, Experiences & Places",
    summery: "Find adventures nearby or in faraway places",
    link: "https://www.airbnb.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/spotify-2.svg",
    name: "Spotify",
    title: "Music for everyone",
    summery: "Listen to millions of songs for free",
    link: "https://www.spotify.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/uber-2.svg",
    name: "Uber",
    title: "Your ride, on demand",
    summery: "Get a ride in minutes",
    link: "https://www.uber.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/linkedin-icon-2.svg",
    name: "LinkedIn",
    title: "Connect to opportunity",
    summery: "Manage your professional identity",
    link: "https://www.linkedin.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/reddit-2.svg",
    name: "Reddit",
    title: "Dive into anything",
    summery: "Find communities you're interested in",
    link: "https://www.reddit.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/pinterest-2.svg",
    name: "Pinterest",
    title: "Discover ideas",
    summery: "Find recipes, home ideas, style inspiration, and other ideas",
    link: "https://www.pinterest.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/slack-new-logo.svg",
    name: "Slack",
    title: "Where work happens",
    summery: "Slack is where work flows",
    link: "https://slack.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/snapchat-2.svg",
    name: "Snapchat",
    title: "Share the moment",
    summery: "Snapchat lets you easily talk with friends, view Live Stories",
    link: "https://www.snapchat.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/tumblr-2.svg",
    name: "Tumblr",
    title: "Follow the blogs you’ve been hearing about",
    summery: "Share your mind and make connections",
    link: "https://www.tumblr.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/github-icon-1.svg",
    name: "GitHub",
    title: "Build software better, together",
    summery:
      "Millions of developers and companies build, ship, and maintain their software",
    link: "https://github.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/paypal-2.svg",
    name: "PayPal",
    title: "Send money, pay online, or set up a merchant account",
    summery: "Safer, simpler way to send and receive money online",
    link: "https://www.paypal.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/whatsapp-icon-2.svg",
    name: "WhatsApp",
    title: "Simple. Secure. Reliable messaging",
    summery: "Send messages, make calls",
    link: "https://www.whatsapp.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/skype-2.svg",
    name: "Skype",
    title: "Stay connected with free video calling",
    summery: "Talk to friends and family for free",
    link: "https://www.skype.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/microsoft-icon-1.svg",
    name: "Microsoft",
    title: "Empowering us all",
    summery: "Find the latest news and information",
    link: "https://www.microsoft.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/airbnb.svg",
    name: "Airbnb",
    title: "Book unique homes and experiences",
    summery: "Find your perfect stay and more",
    link: "https://www.airbnb.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/zoom-2.svg",
    name: "Zoom",
    title: "Video conferencing, cloud phone, webinars, chat, and events",
    summery: "Discover a new way to work together",
    link: "https://zoom.us/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/discord-6.svg",
    name: "Discord",
    title: "Your place to talk",
    summery:
      "Discord is the easiest way to communicate over voice, video, and text",
    link: "https://discord.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/ebay-4.svg",
    name: "eBay",
    title: "Buy it, sell it, love it",
    summery: "Find deals on electronics, fashion, home & garden, toys & more",
    link: "https://www.ebay.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/tiktok-2.svg",
    name: "TikTok",
    title: "Make Your Day",
    summery: "Create and share videos with friends",
    link: "https://www.tiktok.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/spotify-2.svg",
    name: "Spotify",
    title: "Music for everyone",
    summery: "Listen to millions of songs for free",
    link: "https://www.spotify.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/slack-new-logo.svg",
    name: "Slack",
    title: "Where work happens",
    summery: "Slack is where work flows",
    link: "https://slack.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/whatsapp-icon-2.svg",
    name: "WhatsApp",
    title: "Simple. Secure. Reliable messaging",
    summery: "Send messages, make calls",
    link: "https://www.whatsapp.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/yahoo-icon-1.svg",
    name: "Yahoo",
    title: "Yahoo helps you make sense of the world",
    summery: "News, email and search are just the beginning",
    link: "https://www.yahoo.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/shopify-1.svg",
    name: "Shopify",
    title: "Anyone, anywhere, can start a business",
    summery: "Everything you need to start selling online",
    link: "https://www.shopify.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/microsoft-icon-1.svg",
    name: "Microsoft",
    title: "Empowering us all",
    summery: "Find the latest news and information",
    link: "https://www.microsoft.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/uber-2.svg",
    name: "Uber",
    title: "Your ride, on demand",
    summery: "Get a ride in minutes",
    link: "https://www.uber.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/reddit-2.svg",
    name: "Reddit",
    title: "Dive into anything",
    summery: "Find communities you're interested in",
    link: "https://www.reddit.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/airbnb-2.svg",
    name: "Airbnb",
    title: "Vacation Rentals, Homes, Experiences & Places",
    summery: "Find adventures nearby or in faraway places",
    link: "https://www.airbnb.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/linkedin-icon-2.svg",
    name: "LinkedIn",
    title: "Connect to opportunity",
    summery: "Manage your professional identity",
    link: "https://www.linkedin.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/skype-2.svg",
    name: "Skype",
    title: "Stay connected with free video calling",
    summery: "Talk to friends and family for free",
    link: "https://www.skype.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/github-icon-1.svg",
    name: "GitHub",
    title: "Build software better, together",
    summery:
      "Millions of developers and companies build, ship, and maintain their software",
    link: "https://github.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/zoom-2.svg",
    name: "Zoom",
    title: "Video conferencing, cloud phone, webinars, chat, and events",
    summery: "Discover a new way to work together",
    link: "https://zoom.us/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/ebay-4.svg",
    name: "eBay",
    title: "Buy it, sell it, love it",
    summery: "Find deals on electronics, fashion, home & garden, toys & more",
    link: "https://www.ebay.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/discord-6.svg",
    name: "Discord",
    title: "Your place to talk",
    summery:
      "Discord is the easiest way to communicate over voice, video, and text",
    link: "https://discord.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/paypal-2.svg",
    name: "PayPal",
    title: "Send money, pay online, or set up a merchant account",
    summery: "Safer, simpler way to send and receive money online",
    link: "https://www.paypal.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/snapchat-2.svg",
    name: "Snapchat",
    title: "Share the moment",
    summery: "Snapchat lets you easily talk with friends, view Live Stories",
    link: "https://www.snapchat.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/tiktok-2.svg",
    name: "TikTok",
    title: "Make Your Day",
    summery: "Create and share videos with friends",
    link: "https://www.tiktok.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/facebook-3.svg",
    name: "Facebook",
    title: "Connect with friends and the world around you",
    summery: "Share and stay connected with your friends and family",
    link: "https://www.facebook.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/yahoo-icon-1.svg",
    name: "Yahoo",
    title: "Yahoo helps you make sense of the world",
    summery: "News, email and search are just the beginning",
    link: "https://www.yahoo.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/apple-1.svg",
    name: "Apple",
    title: "Think different",
    summery: "Discover the innovative world of Apple",
    link: "https://www.apple.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/instagram-5.svg",
    name: "Instagram",
    title: "Capture and Share the World's Moments",
    summery: "Share what you're into with the people who get you",
    link: "https://www.instagram.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/twitter-6.svg",
    name: "Twitter",
    title: "What's happening?",
    summery: "Join the conversation on Twitter",
    link: "https://twitter.com/",
  },
  {
    imgsrc: "https://cdn.worldvectorlogo.com/logos/pinterest-2.svg",
    name: "Pinterest",
    title: "Discover ideas",
    summery: "Find recipes, home ideas, style inspiration, and other ideas",
    link: "https://www.pinterest.com/",
  },
]

export default Sdata;
